### PR TITLE
Improved test jar removing

### PR DESCRIPTION
**Pull request by vovapolu**

### CODE REVIEW

**Comment by fommil** [comment]
You might need to add some sleep statements into the tests because java is milliscond (sometimes nanosecond) precision but file timestamps might only be 1 second precision.

**Comment by vovapolu** [comment]
@fommil Hmm, difference in tests shows that now some jars are't updated. I can't think of new usage of timestamps in current tests. Should I add more tests for the new feature?

**Comment by fommil** [comment]
That would be good, certainly some semantics might have changed. The existing tests might also be a bit flaky. Just make sure to pause for 1 second before doing any actions that rely on timestamp checks.

**Comment by fommil** [comment]
manually merged

**Pull request merged**
