### PR TITLE
wip

### PR DESCRIPTION
**Pull request by lxol**
Hi Sam, 
I am not sure if you still need that but I spent some time this evening and made a small progress. Manual testing looks good. I managed to create a new directory and it was picked up by the watcher. 
Automatic testing is a nightmare. Only creating a new file is detected consistently  by the test so far...

### CODE REVIEW

**Comment by fommil** [comment]
fantastic! Too late for me to review but this sounds really great.

@aemoncannon look what we got!

**Comment by lxol** [comment]
submitted an update. I managed to orchestrate a test for detecting a new file in a  new directory.
What I noticed is that it takes up to 5 secs to detect a change. Is that okay for Ensime?

**Comment by fommil** [comment]
Hmm, that might be OK. So long as it doesn't eat CPU cycles, it should be OK.

**Comment by fommil** [comment]
I really want to look at this, but I realise the tests and this base project are basically broken right now, so I want to fix that up first before merging.

**Comment by lxol** [comment]
can we just create a separate project for that? 

I published the library locally and started integration with ensime-sever.

**Comment by fommil** [comment]
actually I think you can create it since you're an org member, and you can add it to CI on `fommil.com`. Just copy `ensime-server` or this project as an example for `.drone.yml` (I'll add `.drone.sec` later) and make sure to use the v2 docker base.

**Comment by lxol** [comment]
ok

**Comment by fommil** [comment]
very sorry I've not got round to this tonight... fighting multiple high priority things that I want to get done. Arghh!

**Comment by fommil** [comment]
@lxol actually, I have 10 minutes now, I'll do it.

**Comment by fommil** [comment]
@lxol ok, set up here! https://github.com/ensime/java7-file-watcher :smile:

**Pull request closed without merging**
